import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import Web3Modal from "web3modal";
import WalletConnect from "@walletconnect/web3-provider";

let web3Modal;
const infuraId = process.env.REACT_APP_INFURA_ID;

const providerOptions = {
  walletconnect: {
    package: WalletConnect,
    options: {
      infuraId,
    },
  },
};

export default function Home() {
  async function connect() {
    web3Modal = new Web3Modal({
      cacheProvider: false,
      providerOptions, //requires
    });
    const web3ModalProvider = await web3Modal.connect();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => connect()}>connect</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
